### ISSUE TITLE
Get information from non-visible page

### ISSUE THREAD

**Issue by anayrat** [credativ/toastinfo#5]
Hello,

Huge thank you for your extension, it helped me to work on a toast corruption.

However, I try to find a chunk_id and if a tuple is toasted without reading the toast (it is corrupted) on a non-visible page.

I wonder if it is possible to read raw data from pageinspect and give it to toastinfo ?

Thanks

**Comment by df7cb** [comment]
Hi Adrien,

pageinspect doesn't return data in a way that is actually usable, but you can use pg_dirtyread:

```
create table foo (id int, t text);
insert into foo values (1, 'Hallo');
insert into foo values (2, 'Test');
delete from foo where id = 1;

create extension toastinfo;
select id, t, pg_toastinfo(t) from foo;
 id │  t   │     pg_toastinfo     
────┼──────┼──────────────────────
  2 │ Test │ short inline varlena

create extension pg_dirtyread ;
select id, t, pg_toastinfo(t) from pg_dirtyread('foo') as g(id int, t text);
 id │   t   │     pg_toastinfo     
────┼───────┼──────────────────────
  1 │ Hallo │ short inline varlena
  2 │ Test  │ short inline varlena
```

Note that toastinfo has moved to my Github account as I'm no longer working for Credativ:

* https://github.com/df7cb/toastinfo
* https://github.com/df7cb/pg_dirtyread

**Comment by anayrat** [comment]
Oh that's perfect! thanks !
